### ISSUE TITLE
pixel size of videos different

### ISSUE THREAD

**Issue by madswaord** [heismauri/dtiktok#1]
hello sir, 
i found the pixel size of videos download via shortcuts are always 576x1024, but i tried the same link from other web downloader it was 720x1280, with hevc decoder.  i was wondering if we can have this format. thanks for reading this.

**Comment by heismauri** [comment]
Hello there!, can you share a link so I can better understand it?

**Comment by madswaord** [comment]
> Hello there!, can you share a link so I can better understand it?

hello, you can try this link. https://publer.io/tools/media-downloader

**Comment by heismauri** [comment]
Sadly, seems like the endpoint only gives one specific resolution
