### ISSUE TITLE
short link can't work

### ISSUE THREAD

**Issue by EvenCu** [heismauri/dtiktok#2]
short link  like https://vm.tiktok.com/ZM6kaW8L can't work but https://www.tiktok.com/@odaycocaikana/video/728349353065852443 is ok
![Snipaste_2023-12-22_11-19-32](https://github.com/heismauri/dtiktok/assets/13349843/3fbf3965-05dd-4d86-9b87-87e6f5fdd1ff)

**Comment by heismauri** [comment]
Hello there! seems like your short url expired. However, I was able to fix the problem you show on your screenshot.

**Comment by EvenCu** [comment]
it workd now!thank u,sir!
