### ISSUE TITLE
Slight audio delay and/or quality drop

### ISSUE THREAD

**Issue by EpicLPer** [heismauri/dtiktok#3]
Heya,

I've been using this shortcut extensively over the past months and found some occasional weird behavior, tho I'm not sure if this is due to the shortcut/server behind it or from TikTok.

Occasionally on downloaded videos the audio is a few frames ahead than the video, making mouth movements not being in sync anymore. Other times I discovered that the audio quality gets dropped a tiny bit compared to the original on TikTok.

as said I'm not sure if this is the fault of the server converting videos (if it even does so) or if it's simply just how TikTok CDNs store their videos.

Thanks already!

**Comment by heismauri** [comment]
Sometimes TikTok's CDN delivers them in that quality, there is nothing else for me to do.
