### ISSUE TITLE
Shortcut stopped working 

### ISSUE THREAD

**Issue by auggy** [heismauri/dtiktok#4]
The shortcut says the api is down and to contact you on X unfortunately I’m not on that platform. The website also seems to stall. 

I don’t have any logs, let me know if I can offer more information to help.

**Comment by EpicLPer** [comment]
Can confirm, it started working randomly again but now it's mostly just that API error.

**Comment by EZZOisSAVAGE** [comment]
Does it work, mine says error-dtiktok is under maintenance

**Comment by heismauri** [comment]
Should be working by now :)
